//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLEemailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineExpedite
    {
        public int RequestId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string EDPToolNumber { get; set; }
        public string PurchaseOrderToGermany { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<int> QuantityRequested { get; set; }
        public Nullable<System.DateTime> DateSentTimeStamp { get; set; }
        public string Message { get; set; }
        public string Response { get; set; }
        public string Requestor { get; set; }
        public string RequestorPhoneNumber { get; set; }
        public string RequestorEmailAddress { get; set; }
        public string CSNotes { get; set; }
        public string GermanyResponder { get; set; }
    }
}
